spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone:
      GMT+8
    serialization:
      write-date-keys-as-timestamps: false
  zipkin:
    base-url: ${zipkin.url} 
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      min-idle: 5
      maxActive: 20
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,log4j
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connectionProperties: druid.stat.mergeSql=true;
      stat.slowSqlMillis: 5
      # 配置DruidStatFilter
      web-stat-filter:
        enabled: true
        url-pattern: "/*"
        exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*"
      # 配置DruidStatViewServlet
      stat-view-servlet:
        url-pattern: "/druid/*"
        reset-enable: true
        login-username: admin
        login-password: 123456
  main:
      allow-bean-definition-overriding: true
#  redis:
#      host: 10.10.10.52
#      password: luckserver
#      port: 31623
#      database: 11
  session:
      store-type: redis
#  key-redis: #主键模块的redis配置,主要用获取主键
#      host: 10.10.10.52
#      port: 31623
#      database: 1
#      password: luckserver
  rabbitmq:
#      host: 10.10.10.56
#      port: 5672
#      username: guest
#      password: luckserver
#      virtual-host: test2
            # 开启发送确认
      publisher-confirms: true
            # 开启发送失败退回
      publisher-returns: true
      listener:
        direct:
          acknowledge-mode: manual      # 开启ACK
          retry:
            enabled: true #消费者端的重试
        simple:
          retry:
            enabled: true #消费者端的重试
          acknowledge-mode: manual         # 开启ACK
          prefetch: 5  #在单个请求中处理的消息个数，他应该大于等于事务数量
          auto-startup: true  #启动时自动启动容器  true
          default-requeue-rejected: true  #投递失败时是否重新排队
      template:
        reply-timeout: 10000 #超时时间
        retry:
          enabled: true  #设置为true的时候RabbitTemplate(生产端)能够实现重试
          initial-interval: 1000  #第一次与第二次发布消息的时间间隔 1000
          max-attempts: 3 #尝试发布消息的最大数量 3
          max-interval: 10000  #尝试发布消息的最大时间间隔 10000
          multiplier: 1.0  #上一次尝试时间间隔的乘数 1.0
  #指定模板
  thymeleaf:
      cache: false
      prefix: classpath:/apiview/
      suffix: .html
      mode: HTML
  mvc:
      static-path-pattern: /static/**
  freemarker:
      suffix: .ftl
      #cache: true
      charset: utf-8
      template-loader-path: classpath:/mailTemplate/
  elk:
    append:
      url: ${elk.append.url}
  messages:
      basename: i18n/core/corecommon
mybatis:
  mapper-locations: classpath*:mapping/**/*Mapper.xml
  type-aliases-package: com.luckyun.demo.plan.entity
  config-location: classpath:mybatis-config.xml
luckyun:
  debug: ${server.debug}
  mock: 
    auth: eyJpbmRvY25vIjoyLCJzbG9naW5pZCI6ImFkbWluIiwic3Bhc3N3b3JkIjoiZTEwYWRjMzk0OWJhNTlhYmJlNTZlMDU3ZjIwZjg4M2UiLCJzbmFtZSI6IueuoeeQhuWRmCIsImlzdGF0ZSI6MSwiaWNvbXBhbnlpZCI6MSwic2NvbXBhbnlubSI6IuWuieW+veWtpuW6nCIsInJvbGVMaXN0IjpbeyJrZXlJbmRvY25vIjoyLCJpbmRvY25vIjoyLCJzcmVnaWQiOjIsImRyZWd0IjoiMjAxOS0wMS0wMiAxMTozNzoxMSIsImlkZWwiOjAsIml0eXBlaWQiOjIsInNuYW1lIjoi566h55CG5ZGYIiwic2Rlc2NyaWJlIjoi5omA5pyJ55qE5pON5L2c5p2D6ZmQ5ZKM5a6h5om55p2D6ZmQIiwiaXN0YXRlIjoxLCJpc29ydCI6MiwiaWxldmVsIjo1fV0sImRlcHRMaXN0IjpbeyJrZXlJbmRvY25vIjoxMDAxLCJpbmRvY25vIjoxMDAxLCJkcmVndCI6IjIwMTktMDctMTcgMTA6Mzc6MDMiLCJpZGVsIjowLCJzbmFtZSI6IuW+heWyl+acuuaehCIsIml0eXBlIjowLCJjb21wYW55TmFtZSI6IuWkp+i/nuWfuuWcsCIsImljb21wYW55aWQiOjF9XSwib3BlcmF0ZUxpc3RzIjoiIn0= 
#主键初始化过滤
key-table-filter:
  tables: logging_event,logging_event_exception,logging_event_property,sys_user_log,sys_log,sys_log_field
#bpmcommon:
#  bpm-instance-url: ${bpm-instance-url} #工作流地址配置
# security不需登录URL配置
security:
  nologin:
    - /loginin
    - /company/sysCompany/noGetwayReadByUser
    - /base/company/sysCompany/noGetwayReadByUser
    - /oss/**
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
ribbon:
    ReadTimeout: 60000
    ConnectionTimeout: 60000
application:
  servernm: 
    luckyun-base: luckyun-base
    luckyun-auth: luckyun-auth
oss:
  prefix-url: /oss #可以是前端地址:localhost:8000/api;也可以是后台网关地址localhost:8080
